--- #YAML:1.0
name:                Data-Throttler
version:             0.02
abstract:            Limit data throughput
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    DBM::Deep:                     1.0001
    Log::Log4perl:                 1
    Set::IntSpan:                  0
    Text::ASCIITable:              0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <cpan@perlmeister.com>
